# Generated by Django 3.1.7 on 2021-03-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "admin_pin",
                    models.CharField(
                        default="G11oJQL_knhN8YyFwmkc5tuNWiASHMAr4nBHNTvylF0",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "player_pin",
                    models.CharField(
                        default="DG80BXfVXP8hgh1_z7F4wFXTMwiSgFsRvOsPmIWOZ_Q",
                        editable=False,
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("image", models.URLField()),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rent_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "creditor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="game.player",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debits",
                        to="game.player",
                    ),
                ),
                (
                    "real_estate",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.realestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
                (
                    "real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.realestate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="realestate",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="unique_realestate_names"
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="unique_player_names"
            ),
        ),
    ]
