# Generated by Django 3.1.7 on 2021-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="admin_pin",
            field=models.CharField(
                default="IDA2KQESGpFMUN9Ao6cgDNThVDKnivNRrJsHhZE0X3U",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_pin",
            field=models.CharField(
                default="IreYT70-HuwXJE5eun2TSuSPNb3SLCoYRoJyCUEzPQc",
                editable=False,
                max_length=20,
            ),
        ),
    ]
